name: Yerontour
favicon: null
layout_spectrum: 0.10853643715381622
typography_spectrum: 0.42367685912176967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8533629903104156
  lightness: 0.34208166995085776
  saturation: 0.9110699258744717
  rhythmicContrast: 0.8311406595166773
purpose: []
